#!/bin/bash
set -e
cd "${BASH_SOURCE%/*}"/..

SYSTEM_TARGET=$(rustc -vV | grep -e '^host: ' | sed 's/^host: //')
TSAN_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer-14 RUSTFLAGS=-Zsanitizer=thread cargo +nightly test -Zbuild-std --target "$SYSTEM_TARGET" "$@"
